[project]
authors = ["Samuel Ibarra <ing.samuelibarra@gmail.com>"]
channels = [
    "https://prefix.dev/max-nightly",
    "https://prefix.dev/conda-forge",
]
description = "Python static type checker written in Mojo."
name = "moty"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
moty = "mojo src/moty.mojo"
build = "mojo build src/moty.mojo -o mt"
mt = { cmd = "./mt", depends-on = ["build"] }

[dependencies]
mojo = "<1.0.0"
